version: '3.9'

services:

  management-partners-webapi:
    image: management-partners-webapi:debug
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - default
    ports:
      - 6060:80
    build:
      context: .
      dockerfile: Management.Partners.WebApi/Dockerfile
      args:
        VERSION: 1.0.0.0
    depends_on:
      - mssql
    command: ["dotnet", "ef", "database update"]

  mssql:
    image: "mcr.microsoft.com/mssql/server"
    networks:
      - default
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "Alma1234"
      ACCEPT_EULA: "Y"

networks:
  default:
    name: "partner-network"
